name: Reusable - Publish Specification Snapshot

on:
  workflow_call:
    secrets:
      ORG_GITHUB_BOT_TOKEN:
        required: true

jobs:
  reusable-publish-snapshot:
    runs-on: 'ubuntu-latest'

    container:
      image: asciidoctor/docker-asciidoctor:latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Extract repo name, spec version and spec full name
        id: metadata
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          SPEC_NAME=$(sed -n 's/^:doc-ref:[[:space:]]*//p' index.adoc)
          SPEC_VERSION=$(sed -n 's/^:revnumber:[[:space:]]*//p' index.adoc)
          SPEC_FULL_NAME="${SPEC_NAME}_v${SPEC_VERSION}"
          
          echo "repo-name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "spec-version=$SPEC_VERSION" >> $GITHUB_OUTPUT
          echo "spec-full-name=$SPEC_FULL_NAME" >> $GITHUB_OUTPUT

      - name: Check if this version is already released
        run: |
          SNAPSHOT_VERSION=${{ steps.metadata.outputs.spec-version }}
          RELEASE_VERSION=${SNAPSHOT_VERSION%-SNAPSHOT}
          
          if git tag -l | grep -q "^${RELEASE_VERSION}$"; then
            echo "::error::Tag '$RELEASE_VERSION' already exists. Please update the :spec-version: property in adoc file and try again."
            exit 1
          fi

      - name: Generation of HTML and PDF deliverables
        run: |
          SPEC_FULL_NAME=${{ steps.metadata.outputs.spec-full-name }}
          
          mkdir -p generated
          
          asciidoctor \
            -o "generated/${SPEC_FULL_NAME}.html" \
            index.adoc
          
          asciidoctor-pdf \
            -o "generated/${SPEC_FULL_NAME}.pdf" \
            index.adoc

      - name: Update documentation
        uses: calypsonet/calypsonet-actions/actions/update-specification@main  # NOSONAR - Same organization, trusted source
        with:
          repo-name: ${{ steps.metadata.outputs.repo-name }}
          spec-version: ${{ steps.metadata.outputs.spec-version }}
          spec-full-name: ${{ steps.metadata.outputs.spec-full-name }}
          github-bot-token: ${{ secrets.ORG_GITHUB_BOT_TOKEN }}